### ISSUE TITLE
Unable to publish dashboard on central page

### ISSUE THREAD

**Issue by shahmilan34** [pluginsGLPI/metabase#1]
![metabasepublish](https://user-images.githubusercontent.com/31683819/44405450-e286a900-a576-11e8-8021-61fd7905e45a.png)
As shown in above image plugin imported dashboard from metabase but there is no option to publish dashboard on central page.

**Comment by cedric-anne** [comment]
Hi,

Dashboards will be visible in central page for profiles who can access it. You have to define access rights in the `Metabase` tab of profiles.

Regards

**Comment by shahmilan34** [comment]
Done. Solved My issue.
