### ISSUE TITLE
Undefined index: template-tags

### ISSUE THREAD

**Issue by gustavoiorini** [pluginsGLPI/metabase#11]
Hello, when trying to add reports in the dashboard the following error appears:

![error](https://user-images.githubusercontent.com/52221384/60136342-4a4ee700-977a-11e9-967b-28c139d959c1.JPG)

They could guide me about the error.
Thank you

**Comment by cedric-anne** [comment]
Hi,

Which version of metabase do you use ?

To be compatible with 0.32 version, I had to change some keys when handling Metabase API results (see https://github.com/pluginsGLPI/metabase/pull/9 ).

Regards

**Comment by gustavoiorini** [comment]
thanks, I could solve it
