### ISSUE TITLE
No dashboard and questions generated

### ISSUE THREAD

**Issue by TOH2F** [pluginsGLPI/metabase#21]
Hello,

I'm using GPLI 9.4.6 and the metabase 1.0.0 plugin. The connection is going well, the only problem is that no dashboards are generated. How to do ?

![image](https://user-images.githubusercontent.com/60504041/86341342-75ee9200-bc56-11ea-9a16-324da7b9eb5d.png)

**Comment by stonebuzz** [comment]
Hi @TOH2F 

This option is for developer.

If you develop your own dashbaords / reports (in json format)

you can put them in the "dahsboards" and "reports" folders of the plugin, and generate it in metabase with this option.

Best regards

**Comment by stonebuzz** [comment]
Teclib has developed reports and dashboards available by subscription.
++
