### ISSUE TITLE
metabase throws vendor/autoload.php as missing file or directory. 

### ISSUE THREAD

**Issue by yogeshbhoopathy** [pluginsGLPI/metabase#22]
PHP Warning: include_once(/var/www/html/glpi/plugins/metabase/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/glpi/plugins/metabase/setup.php at line 58
PHP Warning: include_once(): Failed opening '/var/www/html/glpi/plugins/metabase/vendor/autoload.php' for inclusion (include_path='.:/usr/share/php') in /var/www/html/glpi/plugins/metabase/setup.php at line 58

I see that the vendor folder has been added to the .gitignore file, so it's not pushed to the repo

**Comment by cedric-anne** [comment]
Hi,

Indeed, the vendor directory is not included in reprository. You must either use composer to fetch dependencies, either download the .tar.bz2 archive release that contains dependencies.

Regards
